version: '3'

services:
  nuxt:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SENTRY_DSN: ${SENTRY_DSN}
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
        CTF_SPACE_ID: ${CTF_SPACE_ID}
        CTF_CDA_ACCESS_TOKEN: ${CTF_CDA_ACCESS_TOKEN}
        RELEASE_VERSION: local
    ports:
      - 3000:8080
