export const Post: string
export const preview: string
export const inner: string
export const header: string
export const body: string
export const socialLinks: string
export const content: string
export const relatedPosts: string
export const relatedPostsLabel: string
