export const token: string
export const comment: string
export const prolog: string
export const doctype: string
export const cdata: string
export const punctuation: string
export const namespace: string
export const property: string
export const tag: string
export const boolean: string
export const number: string
export const constant: string
export const symbol: string
export const deleted: string
export const selector: string
export const string: string
export const char: string
export const builtin: string
export const inserted: string
export const operator: string
export const entity: string
export const url: string
export const style: string
export const atrule: string
export const keyword: string
export const regex: string
export const important: string
export const variable: string
export const bold: string
export const italic: string
